In [1]:
import tensorflow as tf

import numpy as np

In [2]:
train = np.array([*range(1, 7)], dtype="float")

label = train * 0.5 + 0.5

train

array([1., 2., 3., 4., 5., 6.])

In [3]:
label

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [ ]:
model = tf.keras.Sequential()

layers = tf.keras.layers.Dense(1, input_shape=(1,))

model.add(layers)

In [5]:
model.compile(optimizer="sgd", loss="mse")

In [6]:
model.get_weights()

[array([[0.02760422]], dtype=float32), array([0.], dtype=float32)]

In [ ]:
model.fit(train, label, epochs=1000, verbose=0)

In [8]:
model.get_weights()

[array([[0.5022296]], dtype=float32), array([0.4904548], dtype=float32)]

In [9]:
logits = model.predict(np.array([7.0]), verbose=0)

logits

array([[4.0060616]], dtype=float32)